development:
  adapter: postgresql
  encoding: unicode
  database: numerology_development
  pool: 5
  host: localhost
  username: postgres
  password: shilynb2
    
test:
  adapter: postgresql
  encoding: unicode
  database: numerology_test
  pool: 5
  host: localhost
  username: postgres
  password: shilynb2